module registry_global

// Generated by scripts/generate-relational-model.py. Do not edit by hand.
// Structural satisfiability does not establish full prose-semantic parity.

abstract sig Term { dependsOn: set Term }
one sig T_Absence extends Term {}
one sig T_Presence extends Term {}
one sig T_Missingness extends Term {}
one sig T_Reality extends Term {}
one sig T_Difference extends Term {}
one sig T_Relation extends Term {}
one sig T_Configuration extends Term {}
one sig T_State extends Term {}
one sig T_Direction extends Term {}
one sig T_Transformation extends Term {}
one sig T_Change extends Term {}
one sig T_Feeds extends Term {}
one sig T_CausalPath extends Term {}
one sig T_Invariant extends Term {}
one sig T_Persistence extends Term {}
one sig T_Constraint extends Term {}
one sig T_Entity extends Term {}
one sig T_Boundary extends Term {}
one sig T_Environment extends Term {}
one sig T_Representation extends Term {}
one sig T_Scope extends Term {}
one sig T_Specification extends Term {}
one sig T_Rule extends Term {}
one sig T_Sign extends Term {}
one sig T_Symbol extends Term {}
one sig T_Language extends Term {}
one sig T_Map extends Term {}
one sig T_Reference extends Term {}
one sig T_Sense extends Term {}
one sig T_Perception extends Term {}
one sig T_Record extends Term {}
one sig T_Observation extends Term {}
one sig T_Memory extends Term {}
one sig T_Model extends Term {}
one sig T_Action extends Term {}
one sig T_Consequence extends Term {}
one sig T_Interpretation extends Term {}
one sig T_Agent extends Term {}
one sig T_Agency extends Term {}
one sig T_Tool extends Term {}
one sig T_Capability extends Term {}
one sig T_Interior extends Term {}
one sig T_Exposure extends Term {}
one sig T_Flow extends Term {}
one sig T_Interface extends Term {}
one sig T_Claim extends Term {}
one sig T_Witness extends Term {}
one sig T_Control extends Term {}
one sig T_Order extends Term {}
one sig T_Standing extends Term {}
one sig T_Recognition extends Term {}
one sig T_Principal extends Term {}
one sig T_ActsFor extends Term {}
one sig T_CountsAs extends Term {}
one sig T_Authority extends Term {}
one sig T_PermissionClaim extends Term {}
one sig T_Declaration extends Term {}
one sig T_Grant extends Term {}
one sig T_Admission extends Term {}
one sig T_Permission extends Term {}
one sig T_Revocation extends Term {}
one sig T_PermissionExercise extends Term {}
one sig T_Exercisability extends Term {}
one sig T_FullyExercisablePermission extends Term {}
one sig T_Enforcement extends Term {}
one sig T_Role extends Term {}
one sig T_AdmissibilityRule extends Term {}
one sig T_IndependentFor extends Term {}
one sig T_Evidence extends Term {}
one sig T_Attestation extends Term {}
one sig T_Institution extends Term {}
one sig T_Center extends Term {}
one sig T_Organ extends Term {}
one sig T_CanonicalSystem extends Term {}
one sig T_ShadowSystem extends Term {}
one sig T_Person extends Term {}
one sig T_Receipt extends Term {}
one sig T_Ledger extends Term {}
one sig T_Polity extends Term {}
one sig T_ConstitutedExercise extends Term {}
one sig T_ConstituentExercise extends Term {}
one sig T_ConstituentPower extends Term {}
one sig T_ConsciousnessAttribution extends Term {}
one sig T_ConsciousnessDesignation extends Term {}
one sig T_Operationalization extends Term {}
one sig T_World extends Term {}
one sig T_Substrate extends Term {}
one sig T_Truth extends Term {}
one sig T_Trust extends Term {}
one sig T_Alignment extends Term {}
one sig T_Intelligence extends Term {}
one sig T_OperativeKnowledge extends Term {}
one sig T_KnowledgeTransmission extends Term {}
one sig T_FactiveOperativeKnowledge extends Term {}
one sig T_WarrantedKnowledge extends Term {}
one sig T_MoralStatusAttribution extends Term {}
one sig T_MoralPersonhoodDesignation extends Term {}
one sig T_ConstituentSovereignty extends Term {}
one sig T_ConstitutedSovereignty extends Term {}
one sig T_BoundarySovereignty extends Term {}
one sig T_ExternalSovereignty extends Term {}
one sig T_Preference extends Term {}
one sig T_UtilityMeasure extends Term {}
one sig T_Price extends Term {}

abstract sig Commitment { dependsOnTerm: set Term, dependsOnCommitment: set Commitment }
one sig K_A1 extends Commitment {}
one sig K_A2 extends Commitment {}
one sig K_A3 extends Commitment {}
one sig K_A4 extends Commitment {}
one sig K_A5 extends Commitment {}
one sig K_U1 extends Commitment {}
one sig K_Pj1 extends Commitment {}
one sig K_Pj2 extends Commitment {}
one sig K_Pj3 extends Commitment {}
one sig K_Pj4 extends Commitment {}
one sig K_H1 extends Commitment {}
one sig K_C1 extends Commitment {}
one sig K_C2 extends Commitment {}
one sig K_C3 extends Commitment {}
one sig K_C4 extends Commitment {}
one sig K_C5 extends Commitment {}
one sig K_C6 extends Commitment {}
one sig K_C7 extends Commitment {}
one sig K_C8 extends Commitment {}
one sig K_C9 extends Commitment {}
one sig K_C10 extends Commitment {}
one sig K_C11 extends Commitment {}
one sig K_C12 extends Commitment {}
one sig K_C13 extends Commitment {}
one sig K_C14 extends Commitment {}
one sig K_C15 extends Commitment {}
one sig K_C16 extends Commitment {}
one sig K_C17 extends Commitment {}
one sig K_C18 extends Commitment {}
one sig K_C19 extends Commitment {}
one sig K_C20 extends Commitment {}
one sig K_C21 extends Commitment {}
one sig K_C22 extends Commitment {}
one sig K_C23 extends Commitment {}

abstract sig Slot {}
one sig Slot0, Slot1, Slot2, Slot3, Slot4, Slot5, Slot6, Slot7, Slot8, Slot9, Slot10 extends Slot {}
abstract sig RelationDef { roles: set Slot, expects: Slot -> set Term, produces: one Term }
one sig R_directs extends RelationDef {}
one sig R_feeds extends RelationDef {}
one sig R_persists extends RelationDef {}
one sig R_senses extends RelationDef {}
one sig R_remembers extends RelationDef {}
one sig R_interprets extends RelationDef {}
one sig R_acts extends RelationDef {}
one sig R_uses extends RelationDef {}
one sig R_claims extends RelationDef {}
one sig R_specifies extends RelationDef {}
one sig R_observes extends RelationDef {}
one sig R_controls extends RelationDef {}
one sig R_recognizes extends RelationDef {}
one sig R_actsFor extends RelationDef {}
one sig R_countsAs extends RelationDef {}
one sig R_authorizes extends RelationDef {}
one sig R_declares extends RelationDef {}
one sig R_grants extends RelationDef {}
one sig R_admits extends RelationDef {}
one sig R_permits extends RelationDef {}
one sig R_revokes extends RelationDef {}
one sig R_exercises extends RelationDef {}
one sig R_isExercisable extends RelationDef {}
one sig R_enforces extends RelationDef {}
one sig R_independentFor extends RelationDef {}
one sig R_attests extends RelationDef {}
one sig R_institutes extends RelationDef {}
one sig R_constitutes extends RelationDef {}
one sig R_attributesConsciousness extends RelationDef {}
one sig R_designatesConsciousness extends RelationDef {}
one sig R_operationalizes extends RelationDef {}
one sig R_composesWorld extends RelationDef {}
one sig R_servesAsSubstrate extends RelationDef {}
one sig R_isTrue extends RelationDef {}
one sig R_trusts extends RelationDef {}
one sig R_alignsUnder extends RelationDef {}
one sig R_actsIntelligently extends RelationDef {}
one sig R_knowsOperatively extends RelationDef {}
one sig R_transmitsKnowledge extends RelationDef {}
one sig R_knowsFactively extends RelationDef {}
one sig R_knowsWarrantedly extends RelationDef {}
one sig R_attributesMoralStatus extends RelationDef {}
one sig R_designatesMoralPersonhood extends RelationDef {}
one sig R_exercisesConstituentSovereignty extends RelationDef {}
one sig R_holdsConstitutedSovereignty extends RelationDef {}
one sig R_holdsBoundarySovereignty extends RelationDef {}
one sig R_recognizesExternalSovereignty extends RelationDef {}
one sig R_prefers extends RelationDef {}
one sig R_measuresUtility extends RelationDef {}
one sig R_prices extends RelationDef {}

abstract sig Node { classifies: some Term }
one sig N_Presence extends Node {}
one sig N_Missingness extends Node {}
one sig N_Reality extends Node {}
one sig N_Difference extends Node {}
one sig N_Relation extends Node {}
one sig N_Configuration extends Node {}
one sig N_State extends Node {}
one sig N_Direction extends Node {}
one sig N_Transformation extends Node {}
one sig N_Change extends Node {}
one sig N_Feeds extends Node {}
one sig N_CausalPath extends Node {}
one sig N_Invariant extends Node {}
one sig N_Persistence extends Node {}
one sig N_Constraint extends Node {}
one sig N_Entity extends Node {}
one sig N_Boundary extends Node {}
one sig N_Environment extends Node {}
one sig N_Representation extends Node {}
one sig N_Scope extends Node {}
one sig N_Specification extends Node {}
one sig N_Rule extends Node {}
one sig N_Sign extends Node {}
one sig N_Symbol extends Node {}
one sig N_Language extends Node {}
one sig N_Map extends Node {}
one sig N_Reference extends Node {}
one sig N_Sense extends Node {}
one sig N_Perception extends Node {}
one sig N_Record extends Node {}
one sig N_Observation extends Node {}
one sig N_Memory extends Node {}
one sig N_Model extends Node {}
one sig N_Action extends Node {}
one sig N_Consequence extends Node {}
one sig N_Interpretation extends Node {}
one sig N_Agent extends Node {}
one sig N_Agency extends Node {}
one sig N_Tool extends Node {}
one sig N_Capability extends Node {}
one sig N_Interior extends Node {}
one sig N_Exposure extends Node {}
one sig N_Flow extends Node {}
one sig N_Interface extends Node {}
one sig N_Claim extends Node {}
one sig N_Witness extends Node {}
one sig N_Control extends Node {}
one sig N_Order extends Node {}
one sig N_Standing extends Node {}
one sig N_Recognition extends Node {}
one sig N_Principal extends Node {}
one sig N_ActsFor extends Node {}
one sig N_CountsAs extends Node {}
one sig N_Authority extends Node {}
one sig N_PermissionClaim extends Node {}
one sig N_Declaration extends Node {}
one sig N_Grant extends Node {}
one sig N_Admission extends Node {}
one sig N_Permission extends Node {}
one sig N_Revocation extends Node {}
one sig N_PermissionExercise extends Node {}
one sig N_Exercisability extends Node {}
one sig N_FullyExercisablePermission extends Node {}
one sig N_Enforcement extends Node {}
one sig N_Role extends Node {}
one sig N_AdmissibilityRule extends Node {}
one sig N_IndependentFor extends Node {}
one sig N_Evidence extends Node {}
one sig N_Attestation extends Node {}
one sig N_Institution extends Node {}
one sig N_Center extends Node {}
one sig N_Organ extends Node {}
one sig N_CanonicalSystem extends Node {}
one sig N_ShadowSystem extends Node {}
one sig N_Person extends Node {}
one sig N_Receipt extends Node {}
one sig N_Ledger extends Node {}
one sig N_Polity extends Node {}
one sig N_ConstitutedExercise extends Node {}
one sig N_ConstituentExercise extends Node {}
one sig N_ConstituentPower extends Node {}
one sig N_ConsciousnessAttribution extends Node {}
one sig N_ConsciousnessDesignation extends Node {}
one sig N_Operationalization extends Node {}
one sig N_World extends Node {}
one sig N_Substrate extends Node {}
one sig N_Truth extends Node {}
one sig N_Trust extends Node {}
one sig N_Alignment extends Node {}
one sig N_Intelligence extends Node {}
one sig N_OperativeKnowledge extends Node {}
one sig N_KnowledgeTransmission extends Node {}
one sig N_FactiveOperativeKnowledge extends Node {}
one sig N_WarrantedKnowledge extends Node {}
one sig N_MoralStatusAttribution extends Node {}
one sig N_MoralPersonhoodDesignation extends Node {}
one sig N_ConstituentSovereignty extends Node {}
one sig N_ConstitutedSovereignty extends Node {}
one sig N_BoundarySovereignty extends Node {}
one sig N_ExternalSovereignty extends Node {}
one sig N_Preference extends Node {}
one sig N_UtilityMeasure extends Node {}
one sig N_Price extends Node {}
one sig N_Alt_Entity extends Node {}
one sig N_Alt_OperativeKnowledge extends Node {}
one sig N_Alt_Order extends Node {}
one sig N_Alt_State extends Node {}
one sig JoinedCausal, JoinedInstitutional extends Node {}
one sig Counterexample_C14_15 extends Node {}

abstract sig RelationWitness {
  kind: one RelationDef,
  arguments: Slot -> lone Node,
  output: one Node
}
one sig W_directs extends RelationWitness {}
one sig W_feeds extends RelationWitness {}
one sig W_persists extends RelationWitness {}
one sig W_senses extends RelationWitness {}
one sig W_remembers extends RelationWitness {}
one sig W_interprets extends RelationWitness {}
one sig W_acts extends RelationWitness {}
one sig W_uses extends RelationWitness {}
one sig W_claims extends RelationWitness {}
one sig W_specifies extends RelationWitness {}
one sig W_observes extends RelationWitness {}
one sig W_controls extends RelationWitness {}
one sig W_recognizes extends RelationWitness {}
one sig W_actsFor extends RelationWitness {}
one sig W_countsAs extends RelationWitness {}
one sig W_authorizes extends RelationWitness {}
one sig W_declares extends RelationWitness {}
one sig W_grants extends RelationWitness {}
one sig W_admits extends RelationWitness {}
one sig W_permits extends RelationWitness {}
one sig W_revokes extends RelationWitness {}
one sig W_exercises extends RelationWitness {}
one sig W_isExercisable extends RelationWitness {}
one sig W_enforces extends RelationWitness {}
one sig W_independentFor extends RelationWitness {}
one sig W_attests extends RelationWitness {}
one sig W_institutes extends RelationWitness {}
one sig W_constitutes extends RelationWitness {}
one sig W_attributesConsciousness extends RelationWitness {}
one sig W_designatesConsciousness extends RelationWitness {}
one sig W_operationalizes extends RelationWitness {}
one sig W_composesWorld extends RelationWitness {}
one sig W_servesAsSubstrate extends RelationWitness {}
one sig W_isTrue extends RelationWitness {}
one sig W_trusts extends RelationWitness {}
one sig W_alignsUnder extends RelationWitness {}
one sig W_actsIntelligently extends RelationWitness {}
one sig W_knowsOperatively extends RelationWitness {}
one sig W_transmitsKnowledge extends RelationWitness {}
one sig W_knowsFactively extends RelationWitness {}
one sig W_knowsWarrantedly extends RelationWitness {}
one sig W_attributesMoralStatus extends RelationWitness {}
one sig W_designatesMoralPersonhood extends RelationWitness {}
one sig W_exercisesConstituentSovereignty extends RelationWitness {}
one sig W_holdsConstitutedSovereignty extends RelationWitness {}
one sig W_holdsBoundarySovereignty extends RelationWitness {}
one sig W_recognizesExternalSovereignty extends RelationWitness {}
one sig W_prefers extends RelationWitness {}
one sig W_measuresUtility extends RelationWitness {}
one sig W_prices extends RelationWitness {}

fact ExactRegistryMetadata {
  T_Absence.dependsOn = none
  T_Presence.dependsOn = T_Absence
  T_Missingness.dependsOn = T_Presence
  T_Reality.dependsOn = T_Presence
  T_Difference.dependsOn = T_Presence + T_Reality
  T_Relation.dependsOn = T_Presence
  T_Configuration.dependsOn = T_Presence + T_Relation
  T_State.dependsOn = T_Configuration
  T_Direction.dependsOn = T_Relation + T_State
  T_Transformation.dependsOn = T_Relation + T_State + T_Direction
  T_Change.dependsOn = T_Difference + T_State + T_Transformation
  T_Feeds.dependsOn = T_Relation + T_State
  T_CausalPath.dependsOn = T_Transformation + T_Direction + T_Feeds + T_State
  T_Invariant.dependsOn = T_Relation + T_Configuration + T_Transformation
  T_Persistence.dependsOn = T_Invariant + T_State
  T_Constraint.dependsOn = T_Persistence + T_Relation + T_Transformation
  T_Entity.dependsOn = T_Configuration + T_Persistence + T_Invariant
  T_Boundary.dependsOn = T_Configuration + T_Constraint + T_Invariant + T_Persistence + T_Entity
  T_Environment.dependsOn = T_Presence + T_Entity + T_Boundary
  T_Representation.dependsOn = T_Presence + T_Relation + T_Configuration
  T_Scope.dependsOn = T_Presence + T_Relation + T_State + T_Transformation + T_Representation + T_Constraint
  T_Specification.dependsOn = T_Representation + T_Scope
  T_Rule.dependsOn = T_Specification + T_Constraint + T_Transformation
  T_Sign.dependsOn = T_Representation + T_Presence + T_Relation + T_Change
  T_Symbol.dependsOn = T_Representation
  T_Language.dependsOn = T_Persistence + T_Symbol + T_Rule + T_State
  T_Map.dependsOn = T_Representation + T_Reality
  T_Reference.dependsOn = T_Map + T_Specification + T_Scope + T_Constraint
  T_Sense.dependsOn = T_Constraint + T_Entity + T_Boundary + T_Difference + T_Environment + T_CausalPath
  T_Perception.dependsOn = T_State + T_Sense
  T_Record.dependsOn = T_Persistence + T_Representation + T_State + T_Relation + T_Change
  T_Observation.dependsOn = T_Record + T_Specification + T_CausalPath + T_Environment + T_Sense + T_Reality
  T_Memory.dependsOn = T_Record + T_Persistence + T_State + T_Entity
  T_Model.dependsOn = T_Configuration + T_Representation + T_Transformation + T_Perception + T_Memory + T_State
  T_Action.dependsOn = T_Transformation + T_Entity + T_Boundary + T_CausalPath + T_State
  T_Consequence.dependsOn = T_Change + T_CausalPath + T_Action
  T_Interpretation.dependsOn = T_Transformation + T_Entity + T_Perception + T_Memory + T_Model + T_Action
  T_Agent.dependsOn = T_Entity + T_Interpretation + T_Action
  T_Agency.dependsOn = T_Relation + T_Agent + T_Interpretation + T_Action
  T_Tool.dependsOn = T_Entity + T_Agent + T_CausalPath + T_Action
  T_Capability.dependsOn = T_Action + T_Agent + T_Constraint
  T_Interior.dependsOn = T_Entity + T_State + T_Transformation + T_Specification + T_Boundary
  T_Exposure.dependsOn = T_Transformation + T_Interior + T_State + T_Boundary
  T_Flow.dependsOn = T_Transformation + T_Relation
  T_Interface.dependsOn = T_Boundary + T_Transformation + T_Representation + T_Entity
  T_Claim.dependsOn = T_Representation + T_Agent + T_Presence + T_Relation + T_Configuration + T_Record + T_Scope
  T_Witness.dependsOn = T_Entity + T_Agent + T_Claim + T_Observation
  T_Control.dependsOn = T_Relation + T_Agent + T_Constraint + T_Rule + T_Interface + T_Observation + T_Action + T_CausalPath
  T_Order.dependsOn = T_Configuration + T_Constraint + T_Record + T_Interface + T_Rule + T_Relation + T_Agent + T_Action
  T_Standing.dependsOn = T_Relation + T_Order + T_Record + T_Entity + T_Scope
  T_Recognition.dependsOn = T_Relation + T_Order + T_Standing + T_Entity + T_Rule + T_Scope
  T_Principal.dependsOn = T_Entity + T_Standing + T_Order + T_Action
  T_ActsFor.dependsOn = T_Relation + T_Order + T_Recognition + T_Agent + T_Principal + T_Scope
  T_CountsAs.dependsOn = T_Relation + T_Order + T_Rule + T_Presence + T_Action + T_Claim + T_Record + T_Scope
  T_Authority.dependsOn = T_Relation + T_Order + T_Agent + T_Action + T_CountsAs + T_Principal + T_Scope
  T_PermissionClaim.dependsOn = T_Claim + T_Order + T_Agent + T_Action + T_Scope + T_Principal
  T_Declaration.dependsOn = T_Action + T_Agent + T_Authority + T_Claim + T_Specification + T_Order + T_Scope
  T_Grant.dependsOn = T_Declaration + T_Claim + T_PermissionClaim + T_Authority + T_Principal + T_Agent + T_Scope
  T_Admission.dependsOn = T_CountsAs + T_Order + T_Rule + T_Claim + T_Observation + T_Record
  T_Permission.dependsOn = T_Record + T_Order + T_PermissionClaim + T_Grant + T_Admission + T_Principal + T_Agent + T_Scope
  T_Revocation.dependsOn = T_Declaration + T_Authority + T_Order + T_Permission + T_State
  T_PermissionExercise.dependsOn = T_Action + T_Permission + T_Agent + T_Scope + T_Revocation + T_Order
  T_Exercisability.dependsOn = T_Relation + T_Permission + T_Action + T_Configuration + T_Constraint + T_Scope + T_Order + T_Agent + T_Capability
  T_FullyExercisablePermission.dependsOn = T_Permission + T_Action + T_Scope + T_Exercisability
  T_Enforcement.dependsOn = T_Relation + T_Order + T_Rule + T_Constraint + T_Record + T_Consequence
  T_Role.dependsOn = T_Configuration + T_Order + T_Action + T_Permission + T_Authority + T_Consequence + T_Agent + T_Standing
  T_AdmissibilityRule.dependsOn = T_Rule + T_Specification + T_Declaration + T_Order + T_CountsAs + T_Admission
  T_IndependentFor.dependsOn = T_Relation + T_Witness + T_Agent + T_Claim + T_Observation + T_Order + T_Constraint + T_CausalPath + T_Control + T_Authority + T_AdmissibilityRule + T_Scope
  T_Evidence.dependsOn = T_Observation + T_Witness + T_IndependentFor + T_Agent + T_Claim + T_Order + T_AdmissibilityRule + T_Scope + T_Admission
  T_Attestation.dependsOn = T_Claim + T_Witness + T_Observation + T_Evidence + T_Specification + T_Scope + T_Order + T_IndependentFor
  T_Institution.dependsOn = T_Order + T_Role + T_Record + T_Interface + T_Flow + T_Agent + T_Persistence
  T_Center.dependsOn = T_Entity + T_Institution + T_Flow + T_Constraint
  T_Organ.dependsOn = T_Persistence + T_Configuration + T_Transformation + T_Entity + T_Institution
  T_CanonicalSystem.dependsOn = T_Map + T_Institution + T_Recognition + T_State + T_Relation + T_Action
  T_ShadowSystem.dependsOn = T_Persistence + T_Configuration + T_Record + T_Relation + T_Action + T_CanonicalSystem
  T_Person.dependsOn = T_Entity + T_Order + T_Standing + T_Principal + T_Consequence
  T_Receipt.dependsOn = T_Record + T_Action + T_Agent + T_Authority + T_Permission + T_Scope + T_Consequence
  T_Ledger.dependsOn = T_Record + T_Claim + T_Permission + T_Observation + T_Evidence + T_Attestation + T_Receipt + T_Standing
  T_Polity.dependsOn = T_Agent + T_Institution + T_Action + T_Order
  T_ConstitutedExercise.dependsOn = T_Authority + T_Order
  T_ConstituentExercise.dependsOn = T_Agency + T_Action + T_Order + T_Authority + T_Role + T_Person + T_Claim + T_Boundary
  T_ConstituentPower.dependsOn = T_Persistence + T_Capability + T_Polity + T_ConstituentExercise
  T_ConsciousnessAttribution.dependsOn = T_Agent + T_Claim + T_Entity + T_State + T_Configuration + T_Representation + T_Specification + T_Scope + T_Language + T_Rule + T_Map
  T_ConsciousnessDesignation.dependsOn = T_Relation + T_CountsAs + T_Order + T_Rule + T_Admission + T_Scope + T_Entity + T_State + T_ConsciousnessAttribution
  T_Operationalization.dependsOn = T_Representation + T_Difference + T_Configuration + T_Rule + T_Interface + T_Transformation + T_CausalPath + T_Scope + T_State + T_Agent + T_Interpretation + T_Action + T_Consequence + T_Map + T_Evidence
  T_World.dependsOn = T_Configuration + T_Entity + T_Presence + T_Environment + T_State + T_Relation + T_CausalPath + T_Perception + T_Interpretation + T_Action + T_Constraint + T_Sense + T_Map + T_Reference + T_Scope + T_Invariant + T_Persistence + T_Reality + T_Evidence + T_Claim + T_Order + T_Rule + T_Boundary
  T_Substrate.dependsOn = T_Configuration + T_Scope + T_Persistence + T_Invariant + T_State + T_Transformation + T_Feeds + T_Constraint + T_Difference + T_Representation + T_Entity + T_Environment + T_Tool
  T_Truth.dependsOn = T_Relation + T_Claim + T_Representation + T_Rule + T_Specification + T_Reality + T_Presence + T_Scope + T_Entity + T_Evidence + T_Admission
  T_Trust.dependsOn = T_Relation + T_Entity + T_Boundary + T_Constraint + T_Scope + T_Interior + T_Exposure + T_Consequence + T_Action + T_Claim + T_State + T_CausalPath + T_Control + T_Evidence + T_Permission + T_Authority
  T_Alignment.dependsOn = T_Relation + T_Configuration + T_Presence + T_Specification + T_Scope + T_State + T_Transformation + T_Difference + T_Truth + T_Trust + T_Permission + T_Authority + T_Agency + T_Persistence
  T_Intelligence.dependsOn = T_Capability + T_Agent + T_Model + T_Interpretation + T_Perception + T_Memory + T_Action + T_Consequence + T_Specification + T_State + T_Rule + T_Representation + T_Scope + T_Difference + T_CausalPath + T_Record + T_Tool + T_Substrate
  T_OperativeKnowledge.dependsOn = T_Configuration + T_Record + T_Agent + T_Capability + T_Constraint + T_Rule + T_Model + T_Interpretation + T_CausalPath + T_Action + T_Transformation + T_State + T_Consequence + T_Specification + T_Scope + T_Truth + T_Evidence + T_Difference
  T_KnowledgeTransmission.dependsOn = T_Relation + T_OperativeKnowledge + T_Record + T_CausalPath + T_Specification + T_Scope + T_Configuration + T_State + T_Agent + T_Representation + T_Model + T_Interpretation
  T_FactiveOperativeKnowledge.dependsOn = T_OperativeKnowledge + T_Record + T_Claim + T_Truth + T_Rule + T_Specification + T_Presence + T_Scope
  T_WarrantedKnowledge.dependsOn = T_FactiveOperativeKnowledge + T_Evidence + T_Admission + T_IndependentFor + T_Observation + T_Witness + T_AdmissibilityRule + T_Order + T_Claim
  T_MoralStatusAttribution.dependsOn = T_Claim + T_Agent + T_Entity + T_State + T_Configuration + T_Representation + T_Specification + T_Scope + T_Language + T_Rule + T_Map
  T_MoralPersonhoodDesignation.dependsOn = T_Relation + T_CountsAs + T_Order + T_Rule + T_Admission + T_Scope + T_Entity + T_State + T_MoralStatusAttribution
  T_ConstituentSovereignty.dependsOn = T_Configuration + T_Polity + T_ConstituentPower + T_ConstituentExercise + T_Order + T_Rule + T_Boundary + T_Scope
  T_ConstitutedSovereignty.dependsOn = T_Order + T_Entity + T_Standing + T_Authority + T_Action + T_Scope + T_Recognition + T_Rule
  T_BoundarySovereignty.dependsOn = T_Configuration + T_Polity + T_Entity + T_Control + T_Constraint + T_Transformation + T_Boundary + T_Order + T_Enforcement + T_Difference + T_Consequence + T_State + T_Scope
  T_ExternalSovereignty.dependsOn = T_Relation + T_Order + T_Entity + T_Polity + T_Recognition + T_Standing + T_Principal + T_ActsFor + T_Action + T_Rule + T_Scope
  T_Preference.dependsOn = T_Relation + T_Agent + T_Rule + T_State + T_Consequence + T_Scope
  T_UtilityMeasure.dependsOn = T_Map + T_Relation + T_Rule + T_Specification + T_Scope + T_Preference
  T_Price.dependsOn = T_Relation + T_Ledger + T_Record + T_Order + T_Admission + T_Rule + T_Representation + T_CountsAs + T_Presence + T_State + T_Scope
  K_A1.dependsOnTerm = T_Absence
  K_A1.dependsOnCommitment = none
  K_A2.dependsOnTerm = T_Absence
  K_A2.dependsOnCommitment = none
  K_A3.dependsOnTerm = T_Absence
  K_A3.dependsOnCommitment = none
  K_A4.dependsOnTerm = T_Presence
  K_A4.dependsOnCommitment = K_A3
  K_A5.dependsOnTerm = T_Presence
  K_A5.dependsOnCommitment = none
  K_U1.dependsOnTerm = T_Agency + T_Role + T_Permission + T_Authority + T_Standing
  K_U1.dependsOnCommitment = none
  K_Pj1.dependsOnTerm = T_Agent + T_Sense + T_Memory + T_Model + T_Interpretation + T_Tool + T_Capability + T_Action
  K_Pj1.dependsOnCommitment = K_U1
  K_Pj2.dependsOnTerm = T_Agent + T_Role + T_Permission + T_Authority + T_Standing + T_Order
  K_Pj2.dependsOnCommitment = K_U1
  K_Pj3.dependsOnTerm = T_Missingness + T_Presence
  K_Pj3.dependsOnCommitment = none
  K_Pj4.dependsOnTerm = T_CountsAs + T_Order + T_Rule + T_Scope + T_Presence + T_Claim + T_Action + T_Record
  K_Pj4.dependsOnCommitment = none
  K_H1.dependsOnTerm = T_Flow + T_Center + T_Organ + T_Institution
  K_H1.dependsOnCommitment = none
  K_C1.dependsOnTerm = none
  K_C1.dependsOnCommitment = none
  K_C2.dependsOnTerm = none
  K_C2.dependsOnCommitment = K_C1
  K_C3.dependsOnTerm = none
  K_C3.dependsOnCommitment = K_C1
  K_C4.dependsOnTerm = T_Absence + T_Missingness
  K_C4.dependsOnCommitment = none
  K_C5.dependsOnTerm = T_Reality + T_Map + T_Model + T_Ledger
  K_C5.dependsOnCommitment = none
  K_C6.dependsOnTerm = T_Claim + T_Evidence
  K_C6.dependsOnCommitment = none
  K_C7.dependsOnTerm = T_Capability + T_Standing + T_Authority
  K_C7.dependsOnCommitment = none
  K_C8.dependsOnTerm = T_Interior + T_Exposure
  K_C8.dependsOnCommitment = none
  K_C9.dependsOnTerm = T_Relation + T_Entity + T_Invariant
  K_C9.dependsOnCommitment = none
  K_C10.dependsOnTerm = T_ConsciousnessAttribution + T_ConsciousnessDesignation + T_Missingness + T_Absence + T_Evidence + T_Standing + T_Person + T_Permission + T_Interface + T_Consequence + T_Rule
  K_C10.dependsOnCommitment = none
  K_C11.dependsOnTerm = T_Operationalization + T_Representation + T_Rule + T_Transformation + T_Reality + T_Map + T_Evidence + T_Claim + T_Consequence
  K_C11.dependsOnCommitment = none
  K_C12.dependsOnTerm = T_World + T_Reality + T_Entity + T_Environment + T_Map + T_Reference + T_Invariant + T_Claim
  K_C12.dependsOnCommitment = none
  K_C13.dependsOnTerm = T_Substrate + T_Configuration + T_Scope + T_Transformation + T_Representation + T_Invariant + T_Entity + T_Persistence
  K_C13.dependsOnCommitment = none
  K_C14.dependsOnTerm = T_Truth + T_Entity + T_Evidence + T_Admission + T_Claim + T_Representation + T_Rule + T_Presence + T_Specification
  K_C14.dependsOnCommitment = none
  K_C15.dependsOnTerm = T_Trust + T_Entity + T_Boundary + T_Constraint + T_Exposure + T_Consequence + T_Control + T_Evidence + T_Permission + T_Authority
  K_C15.dependsOnCommitment = none
  K_C16.dependsOnTerm = T_Alignment + T_Specification + T_Scope + T_Truth + T_Trust + T_Permission + T_Authority + T_Agency + T_Consequence + T_Persistence
  K_C16.dependsOnCommitment = none
  K_C17.dependsOnTerm = T_Intelligence + T_Agent + T_Model + T_Interpretation + T_Record + T_Representation + T_Capability + T_Truth + T_Alignment + T_Permission + T_Authority
  K_C17.dependsOnCommitment = none
  K_C18.dependsOnTerm = T_OperativeKnowledge + T_Record + T_Agent + T_Capability + T_Constraint + T_Rule + T_Model + T_Interpretation + T_Action + T_Transformation + T_CausalPath + T_Specification + T_Scope + T_Truth + T_Evidence + T_Consequence
  K_C18.dependsOnCommitment = none
  K_C19.dependsOnTerm = T_KnowledgeTransmission + T_OperativeKnowledge + T_Record + T_Representation + T_Model + T_Interpretation + T_Specification + T_Scope + T_State + T_Agent
  K_C19.dependsOnCommitment = none
  K_C20.dependsOnTerm = T_FactiveOperativeKnowledge + T_WarrantedKnowledge + T_OperativeKnowledge + T_Record + T_Claim + T_Truth + T_Evidence + T_Admission
  K_C20.dependsOnCommitment = none
  K_C21.dependsOnTerm = T_MoralStatusAttribution + T_MoralPersonhoodDesignation + T_Person + T_Standing + T_Permission + T_Interface + T_Consequence + T_Rule
  K_C21.dependsOnCommitment = none
  K_C22.dependsOnTerm = T_ConstituentSovereignty + T_ConstitutedSovereignty + T_BoundarySovereignty + T_ExternalSovereignty + T_Truth + T_Consequence + T_MoralPersonhoodDesignation
  K_C22.dependsOnCommitment = none
  K_C23.dependsOnTerm = T_Preference + T_UtilityMeasure + T_Price + T_CountsAs + T_Action + T_Truth
  K_C23.dependsOnCommitment = none
}

fact ExactRelationMetadata {
  R_directs.roles = Slot0 + Slot1 + Slot2
  R_directs.produces = T_Direction
  R_directs.expects = Slot0->T_Relation + Slot1->T_State + Slot2->T_State
  R_feeds.roles = Slot0 + Slot1 + Slot2
  R_feeds.produces = T_Feeds
  R_feeds.expects = Slot0->T_State + Slot1->T_State + Slot2->T_Specification
  R_persists.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_persists.produces = T_Persistence
  R_persists.expects = Slot0->T_Configuration + Slot1->T_Invariant + Slot2->T_Boundary + Slot3->T_State
  R_senses.roles = Slot0 + Slot1 + Slot2
  R_senses.produces = T_Perception
  R_senses.expects = Slot0->T_Entity + Slot1->T_Difference + Slot2->T_Boundary
  R_remembers.roles = Slot0 + Slot1 + Slot2
  R_remembers.produces = T_Memory
  R_remembers.expects = Slot0->T_Entity + Slot1->T_Record + Slot2->T_State
  R_interprets.roles = Slot0 + Slot1 + Slot2
  R_interprets.produces = T_Interpretation
  R_interprets.expects = Slot0->T_Entity + Slot1->T_Perception + Slot2->T_Memory + Slot2->T_Model
  R_acts.roles = Slot0 + Slot1 + Slot2
  R_acts.produces = T_Action
  R_acts.expects = Slot0->T_Agent + Slot1->T_State + Slot2->T_Boundary
  R_uses.roles = Slot0 + Slot1 + Slot2
  R_uses.produces = T_Tool
  R_uses.expects = Slot0->T_Agent + Slot1->T_Tool + Slot2->T_Action
  R_claims.roles = Slot0 + Slot1 + Slot2
  R_claims.produces = T_Claim
  R_claims.expects = Slot0->T_Agent + Slot1->T_Representation + Slot2->T_Scope
  R_specifies.roles = Slot0 + Slot1 + Slot2
  R_specifies.produces = T_Specification
  R_specifies.expects = Slot0->T_Representation + Slot1->T_Scope + Slot2->T_Rule
  R_observes.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_observes.produces = T_Observation
  R_observes.expects = Slot0->T_Witness + Slot1->T_Environment + Slot2->T_Specification + Slot3->T_CausalPath
  R_controls.roles = Slot0 + Slot1 + Slot2
  R_controls.produces = T_Control
  R_controls.expects = Slot0->T_Agent + Slot1->T_Constraint + Slot1->T_Rule + Slot2->T_Scope
  R_recognizes.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_recognizes.produces = T_Recognition
  R_recognizes.expects = Slot0->T_Order + Slot1->T_Entity + Slot2->T_Rule + Slot3->T_Scope
  R_actsFor.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_actsFor.produces = T_ActsFor
  R_actsFor.expects = Slot0->T_Order + Slot1->T_Agent + Slot2->T_Principal + Slot3->T_Scope
  R_countsAs.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4
  R_countsAs.produces = T_CountsAs
  R_countsAs.expects = Slot0->T_Order + Slot1->T_Rule + Slot2->T_Presence + Slot2->T_Record + Slot3->T_Standing + Slot4->T_Scope
  R_authorizes.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_authorizes.produces = T_Authority
  R_authorizes.expects = Slot0->T_Order + Slot1->T_Agent + Slot2->T_Principal + Slot3->T_Scope
  R_declares.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4
  R_declares.produces = T_Declaration
  R_declares.expects = Slot0->T_Agent + Slot1->T_Authority + Slot2->T_Claim + Slot3->T_Specification + Slot4->T_Order
  R_grants.roles = Slot0 + Slot1
  R_grants.produces = T_Grant
  R_grants.expects = Slot0->T_Declaration + Slot1->T_PermissionClaim
  R_admits.roles = Slot0 + Slot1 + Slot2
  R_admits.produces = T_Admission
  R_admits.expects = Slot0->T_Order + Slot1->T_Rule + Slot2->T_Claim + Slot2->T_Observation + Slot2->T_Record
  R_permits.roles = Slot0 + Slot1 + Slot2
  R_permits.produces = T_Permission
  R_permits.expects = Slot0->T_Order + Slot1->T_PermissionClaim + Slot2->T_Grant
  R_revokes.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_revokes.produces = T_Revocation
  R_revokes.expects = Slot0->T_Order + Slot1->T_Declaration + Slot2->T_Permission + Slot3->T_State
  R_exercises.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_exercises.produces = T_PermissionExercise
  R_exercises.expects = Slot0->T_Permission + Slot1->T_Agent + Slot2->T_Action + Slot3->T_State
  R_isExercisable.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4
  R_isExercisable.produces = T_Exercisability
  R_isExercisable.expects = Slot0->T_Permission + Slot1->T_Action + Slot2->T_State + Slot3->T_Capability + Slot4->T_Configuration + Slot4->T_Constraint
  R_enforces.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_enforces.produces = T_Enforcement
  R_enforces.expects = Slot0->T_Order + Slot1->T_Rule + Slot2->T_Constraint + Slot3->T_Record + Slot3->T_Consequence
  R_independentFor.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4
  R_independentFor.produces = T_IndependentFor
  R_independentFor.expects = Slot0->T_Witness + Slot1->T_Agent + Slot2->T_Claim + Slot3->T_Observation + Slot4->T_Order
  R_attests.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_attests.produces = T_Attestation
  R_attests.expects = Slot0->T_Witness + Slot1->T_Claim + Slot2->T_Specification + Slot3->T_Order
  R_institutes.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_institutes.produces = T_Institution
  R_institutes.expects = Slot0->T_Role + Slot1->T_Record + Slot2->T_Interface + Slot3->T_Flow
  R_constitutes.roles = Slot0 + Slot1 + Slot2
  R_constitutes.produces = T_ConstituentExercise
  R_constitutes.expects = Slot0->T_Polity + Slot1->T_Agency + Slot2->T_Order
  R_attributesConsciousness.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6 + Slot7 + Slot8
  R_attributesConsciousness.produces = T_ConsciousnessAttribution
  R_attributesConsciousness.expects = Slot0->T_Agent + Slot1->T_Entity + Slot2->T_State + Slot3->T_Representation + Slot4->T_Specification + Slot5->T_Language + Slot6->T_Rule + Slot7->T_Map + Slot8->T_Scope
  R_designatesConsciousness.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_designatesConsciousness.produces = T_ConsciousnessDesignation
  R_designatesConsciousness.expects = Slot0->T_Order + Slot1->T_Rule + Slot2->T_ConsciousnessAttribution + Slot3->T_Scope
  R_operationalizes.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5
  R_operationalizes.produces = T_Operationalization
  R_operationalizes.expects = Slot0->T_Representation + Slot1->T_Rule + Slot2->T_Interface + Slot3->T_Scope + Slot4->T_Transformation + Slot5->T_CausalPath
  R_composesWorld.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5
  R_composesWorld.produces = T_World
  R_composesWorld.expects = Slot0->T_Entity + Slot1->T_Environment + Slot2->T_Scope + Slot3->T_Constraint + Slot4->T_CausalPath + Slot5->T_Invariant
  R_servesAsSubstrate.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5
  R_servesAsSubstrate.produces = T_Substrate
  R_servesAsSubstrate.expects = Slot0->T_Configuration + Slot1->T_Scope + Slot2->T_State + Slot3->T_Feeds + Slot4->T_Constraint + Slot5->T_Transformation
  R_isTrue.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6
  R_isTrue.produces = T_Truth
  R_isTrue.expects = Slot0->T_Claim + Slot1->T_Representation + Slot2->T_Rule + Slot3->T_Specification + Slot4->T_Presence + Slot5->T_Reality + Slot6->T_Scope
  R_trusts.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5
  R_trusts.produces = T_Trust
  R_trusts.expects = Slot0->T_Entity + Slot1->T_Entity + Slot2->T_Constraint + Slot3->T_CausalPath + Slot4->T_State + Slot4->T_Exposure + Slot5->T_Scope
  R_alignsUnder.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_alignsUnder.produces = T_Alignment
  R_alignsUnder.expects = Slot0->T_Configuration + Slot1->T_Presence + Slot2->T_Specification + Slot3->T_Scope
  R_actsIntelligently.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6 + Slot7 + Slot8 + Slot9
  R_actsIntelligently.produces = T_Intelligence
  R_actsIntelligently.expects = Slot0->T_Agent + Slot1->T_Perception + Slot2->T_Memory + Slot3->T_Model + Slot4->T_Interpretation + Slot5->T_State + Slot6->T_Action + Slot7->T_Consequence + Slot8->T_Specification + Slot9->T_Scope
  R_knowsOperatively.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6 + Slot7 + Slot8 + Slot9 + Slot10
  R_knowsOperatively.produces = T_OperativeKnowledge
  R_knowsOperatively.expects = Slot0->T_Record + Slot1->T_Agent + Slot2->T_Capability + Slot3->T_Constraint + Slot4->T_Rule + Slot5->T_Model + Slot5->T_Interpretation + Slot6->T_CausalPath + Slot7->T_Action + Slot7->T_Transformation + Slot8->T_State + Slot8->T_Consequence + Slot9->T_Specification + Slot10->T_Scope
  R_transmitsKnowledge.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6 + Slot7
  R_transmitsKnowledge.produces = T_KnowledgeTransmission
  R_transmitsKnowledge.expects = Slot0->T_OperativeKnowledge + Slot1->T_State + Slot2->T_Record + Slot3->T_CausalPath + Slot4->T_OperativeKnowledge + Slot5->T_State + Slot6->T_Specification + Slot7->T_Scope
  R_knowsFactively.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6 + Slot7
  R_knowsFactively.produces = T_FactiveOperativeKnowledge
  R_knowsFactively.expects = Slot0->T_OperativeKnowledge + Slot1->T_Record + Slot2->T_Claim + Slot3->T_Truth + Slot4->T_Rule + Slot5->T_Specification + Slot6->T_Presence + Slot7->T_Scope
  R_knowsWarrantedly.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6
  R_knowsWarrantedly.produces = T_WarrantedKnowledge
  R_knowsWarrantedly.expects = Slot0->T_FactiveOperativeKnowledge + Slot1->T_Evidence + Slot2->T_Observation + Slot3->T_Witness + Slot4->T_AdmissibilityRule + Slot5->T_Order + Slot6->T_Admission
  R_attributesMoralStatus.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6 + Slot7 + Slot8
  R_attributesMoralStatus.produces = T_MoralStatusAttribution
  R_attributesMoralStatus.expects = Slot0->T_Agent + Slot1->T_Entity + Slot2->T_State + Slot3->T_Representation + Slot4->T_Specification + Slot5->T_Language + Slot6->T_Rule + Slot7->T_Map + Slot8->T_Scope
  R_designatesMoralPersonhood.roles = Slot0 + Slot1 + Slot2 + Slot3
  R_designatesMoralPersonhood.produces = T_MoralPersonhoodDesignation
  R_designatesMoralPersonhood.expects = Slot0->T_Order + Slot1->T_Rule + Slot2->T_MoralStatusAttribution + Slot3->T_Scope
  R_exercisesConstituentSovereignty.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4
  R_exercisesConstituentSovereignty.produces = T_ConstituentSovereignty
  R_exercisesConstituentSovereignty.expects = Slot0->T_Polity + Slot1->T_ConstituentPower + Slot2->T_ConstituentExercise + Slot3->T_Order + Slot4->T_Scope
  R_holdsConstitutedSovereignty.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6
  R_holdsConstitutedSovereignty.produces = T_ConstitutedSovereignty
  R_holdsConstitutedSovereignty.expects = Slot0->T_Order + Slot1->T_Entity + Slot2->T_Standing + Slot3->T_Authority + Slot4->T_Action + Slot5->T_Rule + Slot6->T_Scope
  R_holdsBoundarySovereignty.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6
  R_holdsBoundarySovereignty.produces = T_BoundarySovereignty
  R_holdsBoundarySovereignty.expects = Slot0->T_Polity + Slot0->T_Entity + Slot1->T_Boundary + Slot2->T_Constraint + Slot3->T_Transformation + Slot4->T_Enforcement + Slot5->T_Consequence + Slot5->T_State + Slot6->T_Scope
  R_recognizesExternalSovereignty.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6
  R_recognizesExternalSovereignty.produces = T_ExternalSovereignty
  R_recognizesExternalSovereignty.expects = Slot0->T_Order + Slot1->T_Order + Slot2->T_Entity + Slot2->T_Polity + Slot3->T_Principal + Slot4->T_Action + Slot5->T_Rule + Slot6->T_Scope
  R_prefers.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4
  R_prefers.produces = T_Preference
  R_prefers.expects = Slot0->T_Agent + Slot1->T_State + Slot1->T_Consequence + Slot2->T_State + Slot2->T_Consequence + Slot3->T_Rule + Slot4->T_Scope
  R_measuresUtility.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4
  R_measuresUtility.produces = T_UtilityMeasure
  R_measuresUtility.expects = Slot0->T_State + Slot0->T_Consequence + Slot1->T_Map + Slot2->T_Rule + Slot3->T_Specification + Slot4->T_Scope
  R_prices.roles = Slot0 + Slot1 + Slot2 + Slot3 + Slot4 + Slot5 + Slot6 + Slot7
  R_prices.produces = T_Price
  R_prices.expects = Slot0->T_Ledger + Slot1->T_Record + Slot2->T_Order + Slot3->T_Rule + Slot4->T_Representation + Slot5->T_Presence + Slot6->T_State + Slot7->T_Scope
}

fact ExactNodeClassifications {
  N_Presence.classifies = T_Presence
  N_Missingness.classifies = T_Missingness
  N_Reality.classifies = T_Reality
  N_Difference.classifies = T_Difference
  N_Relation.classifies = T_Relation
  N_Configuration.classifies = T_Configuration
  N_State.classifies = T_State
  N_Direction.classifies = T_Direction
  N_Transformation.classifies = T_Transformation
  N_Change.classifies = T_Change
  N_Feeds.classifies = T_Feeds
  N_CausalPath.classifies = T_CausalPath
  N_Invariant.classifies = T_Invariant
  N_Persistence.classifies = T_Persistence
  N_Constraint.classifies = T_Constraint
  N_Entity.classifies = T_Entity
  N_Boundary.classifies = T_Boundary
  N_Environment.classifies = T_Environment
  N_Representation.classifies = T_Representation
  N_Scope.classifies = T_Scope
  N_Specification.classifies = T_Specification
  N_Rule.classifies = T_Rule
  N_Sign.classifies = T_Sign
  N_Symbol.classifies = T_Symbol
  N_Language.classifies = T_Language
  N_Map.classifies = T_Map
  N_Reference.classifies = T_Reference
  N_Sense.classifies = T_Sense
  N_Perception.classifies = T_Perception
  N_Record.classifies = T_Record
  N_Observation.classifies = T_Observation
  N_Memory.classifies = T_Memory
  N_Model.classifies = T_Model
  N_Action.classifies = T_Action
  N_Consequence.classifies = T_Consequence
  N_Interpretation.classifies = T_Interpretation
  N_Agent.classifies = T_Agent
  N_Agency.classifies = T_Agency
  N_Tool.classifies = T_Tool
  N_Capability.classifies = T_Capability
  N_Interior.classifies = T_Interior
  N_Exposure.classifies = T_Exposure
  N_Flow.classifies = T_Flow
  N_Interface.classifies = T_Interface
  N_Claim.classifies = T_Claim
  N_Witness.classifies = T_Witness
  N_Control.classifies = T_Control
  N_Order.classifies = T_Order
  N_Standing.classifies = T_Standing
  N_Recognition.classifies = T_Recognition
  N_Principal.classifies = T_Principal
  N_ActsFor.classifies = T_ActsFor
  N_CountsAs.classifies = T_CountsAs
  N_Authority.classifies = T_Authority
  N_PermissionClaim.classifies = T_PermissionClaim
  N_Declaration.classifies = T_Declaration
  N_Grant.classifies = T_Grant
  N_Admission.classifies = T_Admission
  N_Permission.classifies = T_Permission
  N_Revocation.classifies = T_Revocation
  N_PermissionExercise.classifies = T_Permission + T_PermissionExercise
  N_Exercisability.classifies = T_Exercisability
  N_FullyExercisablePermission.classifies = T_Exercisability + T_FullyExercisablePermission + T_Permission
  N_Enforcement.classifies = T_Enforcement
  N_Role.classifies = T_Role
  N_AdmissibilityRule.classifies = T_AdmissibilityRule
  N_IndependentFor.classifies = T_IndependentFor
  N_Evidence.classifies = T_Evidence
  N_Attestation.classifies = T_Attestation
  N_Institution.classifies = T_Institution
  N_Center.classifies = T_Center
  N_Organ.classifies = T_Organ
  N_CanonicalSystem.classifies = T_CanonicalSystem
  N_ShadowSystem.classifies = T_ShadowSystem
  N_Person.classifies = T_Person
  N_Receipt.classifies = T_Receipt
  N_Ledger.classifies = T_Ledger
  N_Polity.classifies = T_Polity
  N_ConstitutedExercise.classifies = T_ConstitutedExercise
  N_ConstituentExercise.classifies = T_ConstituentExercise
  N_ConstituentPower.classifies = T_ConstituentPower
  N_ConsciousnessAttribution.classifies = T_ConsciousnessAttribution
  N_ConsciousnessDesignation.classifies = T_Admission + T_ConsciousnessDesignation + T_CountsAs
  N_Operationalization.classifies = T_Operationalization
  N_World.classifies = T_World
  N_Substrate.classifies = T_Substrate
  N_Truth.classifies = T_Truth
  N_Trust.classifies = T_Trust
  N_Alignment.classifies = T_Alignment
  N_Intelligence.classifies = T_Intelligence
  N_OperativeKnowledge.classifies = T_OperativeKnowledge
  N_KnowledgeTransmission.classifies = T_KnowledgeTransmission
  N_FactiveOperativeKnowledge.classifies = T_FactiveOperativeKnowledge + T_OperativeKnowledge + T_Truth
  N_WarrantedKnowledge.classifies = T_Admission + T_Evidence + T_FactiveOperativeKnowledge + T_OperativeKnowledge + T_Truth + T_WarrantedKnowledge
  N_MoralStatusAttribution.classifies = T_MoralStatusAttribution
  N_MoralPersonhoodDesignation.classifies = T_Admission + T_CountsAs + T_MoralPersonhoodDesignation
  N_ConstituentSovereignty.classifies = T_ConstituentSovereignty
  N_ConstitutedSovereignty.classifies = T_ConstitutedSovereignty
  N_BoundarySovereignty.classifies = T_BoundarySovereignty
  N_ExternalSovereignty.classifies = T_ExternalSovereignty
  N_Preference.classifies = T_Preference
  N_UtilityMeasure.classifies = T_UtilityMeasure
  N_Price.classifies = T_Price
  N_Alt_Entity.classifies = T_Entity
  N_Alt_OperativeKnowledge.classifies = T_OperativeKnowledge
  N_Alt_Order.classifies = T_Order
  N_Alt_State.classifies = T_State
  JoinedCausal.classifies = T_Presence + T_Relation + T_Configuration + T_State + T_Direction + T_Transformation + T_Change + T_Feeds + T_CausalPath + T_Invariant + T_Persistence + T_Constraint + T_Entity + T_Boundary + T_Environment + T_Representation + T_Scope + T_Specification + T_Rule + T_Perception + T_Record + T_Memory + T_Model + T_Action + T_Consequence + T_Interpretation + T_Agent + T_Capability + T_OperativeKnowledge + T_Truth + T_FactiveOperativeKnowledge
  JoinedInstitutional.classifies = T_Presence + T_Relation + T_Configuration + T_Record + T_Agent + T_Action + T_Representation + T_Scope + T_Specification + T_Rule + T_Claim + T_Order + T_Standing + T_Recognition + T_Principal + T_CountsAs + T_Authority + T_PermissionClaim + T_Declaration + T_Grant + T_Admission + T_Permission + T_PermissionExercise + T_Exercisability + T_FullyExercisablePermission + T_Evidence + T_OperativeKnowledge + T_Truth + T_FactiveOperativeKnowledge + T_WarrantedKnowledge
  Counterexample_C14_15.classifies = T_Claim + T_Representation + T_Rule + T_Presence + T_Specification
}

fact ExactRelationWitnesses {
  W_directs.kind = R_directs
  W_directs.arguments = Slot0->N_Relation + Slot1->N_State + Slot2->N_Alt_State
  W_directs.output = N_Direction
  W_feeds.kind = R_feeds
  W_feeds.arguments = Slot0->N_State + Slot1->N_Alt_State + Slot2->N_Specification
  W_feeds.output = N_Feeds
  W_persists.kind = R_persists
  W_persists.arguments = Slot0->N_Configuration + Slot1->N_Invariant + Slot2->N_Boundary + Slot3->N_State
  W_persists.output = N_Persistence
  W_senses.kind = R_senses
  W_senses.arguments = Slot0->N_Entity + Slot1->N_Difference + Slot2->N_Boundary
  W_senses.output = N_Perception
  W_remembers.kind = R_remembers
  W_remembers.arguments = Slot0->N_Entity + Slot1->N_Record + Slot2->N_State
  W_remembers.output = N_Memory
  W_interprets.kind = R_interprets
  W_interprets.arguments = Slot0->N_Entity + Slot1->N_Perception + Slot2->N_Memory
  W_interprets.output = N_Interpretation
  W_acts.kind = R_acts
  W_acts.arguments = Slot0->N_Agent + Slot1->N_State + Slot2->N_Boundary
  W_acts.output = N_Action
  W_uses.kind = R_uses
  W_uses.arguments = Slot0->N_Agent + Slot1->N_Tool + Slot2->N_Action
  W_uses.output = N_Tool
  W_claims.kind = R_claims
  W_claims.arguments = Slot0->N_Agent + Slot1->N_Representation + Slot2->N_Scope
  W_claims.output = N_Claim
  W_specifies.kind = R_specifies
  W_specifies.arguments = Slot0->N_Representation + Slot1->N_Scope + Slot2->N_Rule
  W_specifies.output = N_Specification
  W_observes.kind = R_observes
  W_observes.arguments = Slot0->N_Witness + Slot1->N_Environment + Slot2->N_Specification + Slot3->N_CausalPath
  W_observes.output = N_Observation
  W_controls.kind = R_controls
  W_controls.arguments = Slot0->N_Agent + Slot1->N_Constraint + Slot2->N_Scope
  W_controls.output = N_Control
  W_recognizes.kind = R_recognizes
  W_recognizes.arguments = Slot0->N_Order + Slot1->N_Entity + Slot2->N_Rule + Slot3->N_Scope
  W_recognizes.output = N_Recognition
  W_actsFor.kind = R_actsFor
  W_actsFor.arguments = Slot0->N_Order + Slot1->N_Agent + Slot2->N_Principal + Slot3->N_Scope
  W_actsFor.output = N_ActsFor
  W_countsAs.kind = R_countsAs
  W_countsAs.arguments = Slot0->N_Order + Slot1->N_Rule + Slot2->N_Presence + Slot3->N_Standing + Slot4->N_Scope
  W_countsAs.output = N_CountsAs
  W_authorizes.kind = R_authorizes
  W_authorizes.arguments = Slot0->N_Order + Slot1->N_Agent + Slot2->N_Principal + Slot3->N_Scope
  W_authorizes.output = N_Authority
  W_declares.kind = R_declares
  W_declares.arguments = Slot0->N_Agent + Slot1->N_Authority + Slot2->N_Claim + Slot3->N_Specification + Slot4->N_Order
  W_declares.output = N_Declaration
  W_grants.kind = R_grants
  W_grants.arguments = Slot0->N_Declaration + Slot1->N_PermissionClaim
  W_grants.output = N_Grant
  W_admits.kind = R_admits
  W_admits.arguments = Slot0->N_Order + Slot1->N_Rule + Slot2->N_Claim
  W_admits.output = N_Admission
  W_permits.kind = R_permits
  W_permits.arguments = Slot0->N_Order + Slot1->N_PermissionClaim + Slot2->N_Grant
  W_permits.output = N_Permission
  W_revokes.kind = R_revokes
  W_revokes.arguments = Slot0->N_Order + Slot1->N_Declaration + Slot2->N_Permission + Slot3->N_State
  W_revokes.output = N_Revocation
  W_exercises.kind = R_exercises
  W_exercises.arguments = Slot0->N_Permission + Slot1->N_Agent + Slot2->N_Action + Slot3->N_State
  W_exercises.output = N_PermissionExercise
  W_isExercisable.kind = R_isExercisable
  W_isExercisable.arguments = Slot0->N_Permission + Slot1->N_Action + Slot2->N_State + Slot3->N_Capability + Slot4->N_Configuration
  W_isExercisable.output = N_Exercisability
  W_enforces.kind = R_enforces
  W_enforces.arguments = Slot0->N_Order + Slot1->N_Rule + Slot2->N_Constraint + Slot3->N_Record
  W_enforces.output = N_Enforcement
  W_independentFor.kind = R_independentFor
  W_independentFor.arguments = Slot0->N_Witness + Slot1->N_Agent + Slot2->N_Claim + Slot3->N_Observation + Slot4->N_Order
  W_independentFor.output = N_IndependentFor
  W_attests.kind = R_attests
  W_attests.arguments = Slot0->N_Witness + Slot1->N_Claim + Slot2->N_Specification + Slot3->N_Order
  W_attests.output = N_Attestation
  W_institutes.kind = R_institutes
  W_institutes.arguments = Slot0->N_Role + Slot1->N_Record + Slot2->N_Interface + Slot3->N_Flow
  W_institutes.output = N_Institution
  W_constitutes.kind = R_constitutes
  W_constitutes.arguments = Slot0->N_Polity + Slot1->N_Agency + Slot2->N_Order
  W_constitutes.output = N_ConstituentExercise
  W_attributesConsciousness.kind = R_attributesConsciousness
  W_attributesConsciousness.arguments = Slot0->N_Agent + Slot1->N_Entity + Slot2->N_State + Slot3->N_Representation + Slot4->N_Specification + Slot5->N_Language + Slot6->N_Rule + Slot7->N_Map + Slot8->N_Scope
  W_attributesConsciousness.output = N_ConsciousnessAttribution
  W_designatesConsciousness.kind = R_designatesConsciousness
  W_designatesConsciousness.arguments = Slot0->N_Order + Slot1->N_Rule + Slot2->N_ConsciousnessAttribution + Slot3->N_Scope
  W_designatesConsciousness.output = N_ConsciousnessDesignation
  W_operationalizes.kind = R_operationalizes
  W_operationalizes.arguments = Slot0->N_Representation + Slot1->N_Rule + Slot2->N_Interface + Slot3->N_Scope + Slot4->N_Transformation + Slot5->N_CausalPath
  W_operationalizes.output = N_Operationalization
  W_composesWorld.kind = R_composesWorld
  W_composesWorld.arguments = Slot0->N_Entity + Slot1->N_Environment + Slot2->N_Scope + Slot3->N_Constraint + Slot4->N_CausalPath + Slot5->N_Invariant
  W_composesWorld.output = N_World
  W_servesAsSubstrate.kind = R_servesAsSubstrate
  W_servesAsSubstrate.arguments = Slot0->N_Configuration + Slot1->N_Scope + Slot2->N_State + Slot3->N_Feeds + Slot4->N_Constraint + Slot5->N_Transformation
  W_servesAsSubstrate.output = N_Substrate
  W_isTrue.kind = R_isTrue
  W_isTrue.arguments = Slot0->N_Claim + Slot1->N_Representation + Slot2->N_Rule + Slot3->N_Specification + Slot4->N_Presence + Slot5->N_Reality + Slot6->N_Scope
  W_isTrue.output = N_Truth
  W_trusts.kind = R_trusts
  W_trusts.arguments = Slot0->N_Entity + Slot1->N_Alt_Entity + Slot2->N_Constraint + Slot3->N_CausalPath + Slot4->N_State + Slot5->N_Scope
  W_trusts.output = N_Trust
  W_alignsUnder.kind = R_alignsUnder
  W_alignsUnder.arguments = Slot0->N_Configuration + Slot1->N_Presence + Slot2->N_Specification + Slot3->N_Scope
  W_alignsUnder.output = N_Alignment
  W_actsIntelligently.kind = R_actsIntelligently
  W_actsIntelligently.arguments = Slot0->N_Agent + Slot1->N_Perception + Slot2->N_Memory + Slot3->N_Model + Slot4->N_Interpretation + Slot5->N_State + Slot6->N_Action + Slot7->N_Consequence + Slot8->N_Specification + Slot9->N_Scope
  W_actsIntelligently.output = N_Intelligence
  W_knowsOperatively.kind = R_knowsOperatively
  W_knowsOperatively.arguments = Slot0->N_Record + Slot1->N_Agent + Slot2->N_Capability + Slot3->N_Constraint + Slot4->N_Rule + Slot5->N_Model + Slot6->N_CausalPath + Slot7->N_Action + Slot8->N_State + Slot9->N_Specification + Slot10->N_Scope
  W_knowsOperatively.output = N_OperativeKnowledge
  W_transmitsKnowledge.kind = R_transmitsKnowledge
  W_transmitsKnowledge.arguments = Slot0->N_OperativeKnowledge + Slot1->N_State + Slot2->N_Record + Slot3->N_CausalPath + Slot4->N_Alt_OperativeKnowledge + Slot5->N_Alt_State + Slot6->N_Specification + Slot7->N_Scope
  W_transmitsKnowledge.output = N_KnowledgeTransmission
  W_knowsFactively.kind = R_knowsFactively
  W_knowsFactively.arguments = Slot0->N_OperativeKnowledge + Slot1->N_Record + Slot2->N_Claim + Slot3->N_Truth + Slot4->N_Rule + Slot5->N_Specification + Slot6->N_Presence + Slot7->N_Scope
  W_knowsFactively.output = N_FactiveOperativeKnowledge
  W_knowsWarrantedly.kind = R_knowsWarrantedly
  W_knowsWarrantedly.arguments = Slot0->N_FactiveOperativeKnowledge + Slot1->N_Evidence + Slot2->N_Observation + Slot3->N_Witness + Slot4->N_AdmissibilityRule + Slot5->N_Order + Slot6->N_Admission
  W_knowsWarrantedly.output = N_WarrantedKnowledge
  W_attributesMoralStatus.kind = R_attributesMoralStatus
  W_attributesMoralStatus.arguments = Slot0->N_Agent + Slot1->N_Entity + Slot2->N_State + Slot3->N_Representation + Slot4->N_Specification + Slot5->N_Language + Slot6->N_Rule + Slot7->N_Map + Slot8->N_Scope
  W_attributesMoralStatus.output = N_MoralStatusAttribution
  W_designatesMoralPersonhood.kind = R_designatesMoralPersonhood
  W_designatesMoralPersonhood.arguments = Slot0->N_Order + Slot1->N_Rule + Slot2->N_MoralStatusAttribution + Slot3->N_Scope
  W_designatesMoralPersonhood.output = N_MoralPersonhoodDesignation
  W_exercisesConstituentSovereignty.kind = R_exercisesConstituentSovereignty
  W_exercisesConstituentSovereignty.arguments = Slot0->N_Polity + Slot1->N_ConstituentPower + Slot2->N_ConstituentExercise + Slot3->N_Order + Slot4->N_Scope
  W_exercisesConstituentSovereignty.output = N_ConstituentSovereignty
  W_holdsConstitutedSovereignty.kind = R_holdsConstitutedSovereignty
  W_holdsConstitutedSovereignty.arguments = Slot0->N_Order + Slot1->N_Entity + Slot2->N_Standing + Slot3->N_Authority + Slot4->N_Action + Slot5->N_Rule + Slot6->N_Scope
  W_holdsConstitutedSovereignty.output = N_ConstitutedSovereignty
  W_holdsBoundarySovereignty.kind = R_holdsBoundarySovereignty
  W_holdsBoundarySovereignty.arguments = Slot0->N_Polity + Slot1->N_Boundary + Slot2->N_Constraint + Slot3->N_Transformation + Slot4->N_Enforcement + Slot5->N_Consequence + Slot6->N_Scope
  W_holdsBoundarySovereignty.output = N_BoundarySovereignty
  W_recognizesExternalSovereignty.kind = R_recognizesExternalSovereignty
  W_recognizesExternalSovereignty.arguments = Slot0->N_Order + Slot1->N_Alt_Order + Slot2->N_Entity + Slot3->N_Principal + Slot4->N_Action + Slot5->N_Rule + Slot6->N_Scope
  W_recognizesExternalSovereignty.output = N_ExternalSovereignty
  W_prefers.kind = R_prefers
  W_prefers.arguments = Slot0->N_Agent + Slot1->N_State + Slot2->N_Alt_State + Slot3->N_Rule + Slot4->N_Scope
  W_prefers.output = N_Preference
  W_measuresUtility.kind = R_measuresUtility
  W_measuresUtility.arguments = Slot0->N_State + Slot1->N_Map + Slot2->N_Rule + Slot3->N_Specification + Slot4->N_Scope
  W_measuresUtility.output = N_UtilityMeasure
  W_prices.kind = R_prices
  W_prices.arguments = Slot0->N_Ledger + Slot1->N_Record + Slot2->N_Order + Slot3->N_Rule + Slot4->N_Representation + Slot5->N_Presence + Slot6->N_State + Slot7->N_Scope
  W_prices.output = N_Price
}

// Dependency edges are exact above. Acyclicity is checked directly from
// the registry by scripts/check-relational-instance.py; asking the SAT
// solver for a transitive closure over 104 fixed terms adds no inhabitant
// evidence and dominates the otherwise finite search.

fact EveryRegisteredConceptIsWitnessedExceptAbsoluteAbsence {
  no node: Node | T_Absence in node.classifies
  all term: Term - T_Absence | some node: Node | term in node.classifies
}

fact EveryDeclaredRelationHasOneTypedWitness {
  all definition: RelationDef | one witness: RelationWitness | witness.kind = definition
  all witness: RelationWitness | {
    witness.arguments.Node = witness.kind.roles
    all slot: witness.kind.roles | some expected: witness.kind.expects[slot] | expected in witness.arguments[slot].classifies
    all slot: Slot - witness.kind.roles | no witness.arguments[slot]
    witness.kind.produces in witness.output.classifies
  }
}

fact PositiveProfileJoins {
  all node: Node | T_PermissionExercise in node.classifies implies T_Permission in node.classifies
  all node: Node | T_FullyExercisablePermission in node.classifies implies T_Permission + T_Exercisability in node.classifies
  all node: Node | T_ConsciousnessDesignation in node.classifies implies T_CountsAs + T_Admission in node.classifies
  all node: Node | T_MoralPersonhoodDesignation in node.classifies implies T_CountsAs + T_Admission in node.classifies
  all node: Node | T_FactiveOperativeKnowledge in node.classifies implies T_OperativeKnowledge + T_Truth in node.classifies
  all node: Node | T_WarrantedKnowledge in node.classifies implies T_FactiveOperativeKnowledge + T_Evidence + T_Admission in node.classifies
}

pred implicationCounterexample[required: set Term, denied: Term] {
  some node: Node | required in node.classifies and denied not in node.classifies
}

pred disjointClasses[left, right: Term] {
  no node: Node | left + right in node.classifies
}

fact EncodedNoCollapseObligations {
  implicationCounterexample[T_Claim, T_Evidence] // C6
  implicationCounterexample[T_Capability, T_Standing] // C7
  implicationCounterexample[T_Standing, T_Capability] // C7
  implicationCounterexample[T_Authority, T_Capability] // C7
  implicationCounterexample[T_ConsciousnessDesignation, T_Standing] // C10
  implicationCounterexample[T_ConsciousnessDesignation, T_Person] // C10
  implicationCounterexample[T_ConsciousnessDesignation, T_Permission] // C10
  implicationCounterexample[T_ConsciousnessDesignation, T_Interface] // C10
  implicationCounterexample[T_ConsciousnessDesignation, T_Consequence] // C10
  implicationCounterexample[T_Operationalization, T_Map] // C11
  implicationCounterexample[T_Operationalization, T_Evidence] // C11
  implicationCounterexample[T_Truth, T_Evidence] // C14
  implicationCounterexample[T_Evidence, T_Truth] // C14
  implicationCounterexample[T_Truth, T_Admission] // C14
  implicationCounterexample[T_Admission, T_Truth] // C14
  implicationCounterexample[T_Claim + T_Representation + T_Rule + T_Presence + T_Specification, T_Truth] // C14
  implicationCounterexample[T_Trust, T_Control] // C15
  implicationCounterexample[T_Trust, T_Evidence] // C15
  implicationCounterexample[T_Permission, T_Trust] // C15
  implicationCounterexample[T_Authority, T_Trust] // C15
  implicationCounterexample[T_Alignment, T_Truth] // C16
  implicationCounterexample[T_Alignment, T_Trust] // C16
  implicationCounterexample[T_Alignment, T_Permission] // C16
  implicationCounterexample[T_Alignment, T_Authority] // C16
  implicationCounterexample[T_Alignment, T_Agency] // C16
  implicationCounterexample[T_Alignment, T_Persistence] // C16
  implicationCounterexample[T_Model, T_Intelligence] // C17
  implicationCounterexample[T_Capability, T_Intelligence] // C17
  implicationCounterexample[T_Intelligence, T_Truth] // C17
  implicationCounterexample[T_Intelligence, T_Authority] // C17
  implicationCounterexample[T_Record, T_OperativeKnowledge] // C18
  implicationCounterexample[T_Truth, T_OperativeKnowledge] // C18
  implicationCounterexample[T_OperativeKnowledge, T_Truth] // C18
  implicationCounterexample[T_OperativeKnowledge, T_Evidence] // C18
  implicationCounterexample[T_Record, T_KnowledgeTransmission] // C19
  implicationCounterexample[T_KnowledgeTransmission, T_Intelligence] // C19
  implicationCounterexample[T_OperativeKnowledge, T_FactiveOperativeKnowledge] // C20
  implicationCounterexample[T_Truth, T_FactiveOperativeKnowledge] // C20
  implicationCounterexample[T_FactiveOperativeKnowledge, T_WarrantedKnowledge] // C20
  implicationCounterexample[T_Evidence, T_WarrantedKnowledge] // C20
  implicationCounterexample[T_MoralPersonhoodDesignation, T_Person] // C21
  implicationCounterexample[T_MoralPersonhoodDesignation, T_Standing] // C21
  implicationCounterexample[T_MoralPersonhoodDesignation, T_Permission] // C21
  implicationCounterexample[T_MoralPersonhoodDesignation, T_Consequence] // C21
  implicationCounterexample[T_Action, T_Preference] // C23
  implicationCounterexample[T_Preference, T_UtilityMeasure] // C23
  implicationCounterexample[T_UtilityMeasure, T_Preference] // C23
  implicationCounterexample[T_Price, T_Preference] // C23
  implicationCounterexample[T_Price, T_UtilityMeasure] // C23
  implicationCounterexample[T_Price, T_Truth] // C23
  disjointClasses[T_Map, T_Reality] // C5
  disjointClasses[T_Model, T_Reality] // C5
  disjointClasses[T_Ledger, T_Reality] // C5
  disjointClasses[T_World, T_Reality] // C12
  disjointClasses[T_World, T_Environment] // C12
  disjointClasses[T_World, T_Map] // C12
  disjointClasses[T_World, T_Reference] // C12
  disjointClasses[T_Substrate, T_Representation] // C13
  disjointClasses[T_Substrate, T_Invariant] // C13
  disjointClasses[T_Substrate, T_Entity] // C13
  implicationCounterexample[T_ConstituentSovereignty, T_ConstitutedSovereignty] // C22
  implicationCounterexample[T_ConstituentSovereignty, T_BoundarySovereignty] // C22
  implicationCounterexample[T_ConstituentSovereignty, T_ExternalSovereignty] // C22
  implicationCounterexample[T_ConstitutedSovereignty, T_ConstituentSovereignty] // C22
  implicationCounterexample[T_ConstitutedSovereignty, T_BoundarySovereignty] // C22
  implicationCounterexample[T_ConstitutedSovereignty, T_ExternalSovereignty] // C22
  implicationCounterexample[T_BoundarySovereignty, T_ConstituentSovereignty] // C22
  implicationCounterexample[T_BoundarySovereignty, T_ConstitutedSovereignty] // C22
  implicationCounterexample[T_BoundarySovereignty, T_ExternalSovereignty] // C22
  implicationCounterexample[T_ExternalSovereignty, T_ConstituentSovereignty] // C22
  implicationCounterexample[T_ExternalSovereignty, T_ConstitutedSovereignty] // C22
  implicationCounterexample[T_ExternalSovereignty, T_BoundarySovereignty] // C22
}

pred NondegenerateGlobalInhabitant {
  disj[N_Presence, N_State, N_Entity, N_Order]
  T_Entity + T_Agent + T_Action in JoinedCausal.classifies
  T_Order + T_Permission + T_Evidence in JoinedInstitutional.classifies
  some disj first, second: RelationWitness |
    some first.arguments[Slot] & second.arguments[Slot]
}

run NondegenerateGlobalInhabitant for 0 Int
